-- SCRIPT POBLADO DE TABLAS

-- POBLADO TABLA ESTADO_CIVIL

INSERT INTO ESTADO_CIVIL VALUES (1,'Casado');
INSERT INTO ESTADO_CIVIL VALUES (2,'Conviviente civil');
INSERT INTO ESTADO_CIVIL VALUES (3,'Soltero');
INSERT INTO ESTADO_CIVIL VALUES (4,'Divorciado');
INSERT INTO ESTADO_CIVIL VALUES (5,'Viudo');
/
 
-- POBLADO TABLA NACIONALIDAD
INSERT INTO NACIONALIDAD VALUES (1, 'Chilena');
INSERT INTO NACIONALIDAD VALUES (2, 'Argentina');
INSERT INTO NACIONALIDAD VALUES (3, 'Canadiense');
INSERT INTO NACIONALIDAD VALUES (4, 'Peruana');
INSERT INTO NACIONALIDAD VALUES (5, 'Boliviana');
/

-- POBLADO TABLA REGION
INSERT INTO REGION VALUES(1, 'de Tarapacá');
INSERT INTO REGION VALUES(2, 'de Antofagasta');
INSERT INTO REGION VALUES(3, 'de Atacama');
INSERT INTO REGION VALUES(4, 'de Coquimbo');
INSERT INTO REGION VALUES(5, 'de Valparaíso');
INSERT INTO REGION VALUES(6, 'de OHiggins');
INSERT INTO REGION VALUES(7, 'del Maule');
INSERT INTO REGION VALUES(8, 'del Biobío');
INSERT INTO REGION VALUES(9, 'de La Araucanía');
INSERT INTO REGION VALUES(10, 'de Los Lagos');
INSERT INTO REGION VALUES(11, 'de Aysén');
INSERT INTO REGION VALUES(12, 'de Magallanes');
INSERT INTO REGION VALUES(13, 'Metropolitana');
INSERT INTO REGION VALUES(14, 'de Los Ríos');
INSERT INTO REGION VALUES(15, 'de Arica y Parinacota');
INSERT INTO REGION VALUES(16, 'de Ñuble');
/