-- SCRIPT POBLADO DE TABLAS

-- POBLADO TABLA ESTADO_CIVIL

-- a lo mejor esta tabla debería tener id fijo, porque la usamos para los insert de más adelante

INSERT INTO ESTADO_CIVIL VALUES (SEQ_ESTADO_CIVIL_ID_ESTADO_CIVIL.NEXTVAL,'Casado');
INSERT INTO ESTADO_CIVIL VALUES (SEQ_ESTADO_CIVIL_ID_ESTADO_CIVIL.NEXTVAL,'Conviviente civil');
INSERT INTO ESTADO_CIVIL VALUES (SEQ_ESTADO_CIVIL_ID_ESTADO_CIVIL.NEXTVAL,'Soltero');
INSERT INTO ESTADO_CIVIL VALUES (SEQ_ESTADO_CIVIL_ID_ESTADO_CIVIL.NEXTVAL,'Divorciado');
INSERT INTO ESTADO_CIVIL VALUES (SEQ_ESTADO_CIVIL_ID_ESTADO_CIVIL.NEXTVAL,'Viudo');
/
 
-- POBLADO TABLA NACIONALIDAD
INSERT INTO NACIONALIDAD VALUES (SEQ_NACIONALIDAD_ID_NACIONALIDAD.NEXTVAL, 'Chilena');
INSERT INTO NACIONALIDAD VALUES (SEQ_NACIONALIDAD_ID_NACIONALIDAD.NEXTVAL, 'Argentina');
INSERT INTO NACIONALIDAD VALUES (SEQ_NACIONALIDAD_ID_NACIONALIDAD.NEXTVAL, 'Canadiense');
INSERT INTO NACIONALIDAD VALUES (SEQ_NACIONALIDAD_ID_NACIONALIDAD.NEXTVAL, 'Australiana');
INSERT INTO NACIONALIDAD VALUES (SEQ_NACIONALIDAD_ID_NACIONALIDAD.NEXTVAL, 'Alemana');
/

-- POBLADO TABLA REGION
INSERT INTO REGION VALUES(1, 'de Tarapacá¡');
INSERT INTO REGION VALUES(2, 'de Antofagasta');
INSERT INTO REGION VALUES(3, 'de Atacama');
INSERT INTO REGION VALUES(4, 'de Coquimbo');
INSERT INTO REGION VALUES(5, 'de Valparaíso');
INSERT INTO REGION VALUES(6, 'de OHiggins');
INSERT INTO REGION VALUES(7, 'del Maule');
INSERT INTO REGION VALUES(8, 'del Biobío');
INSERT INTO REGION VALUES(9, 'de La Araucanía');
INSERT INTO REGION VALUES(10, 'de Los Lagos');
INSERT INTO REGION VALUES(11, 'de Aysén del General Carlos Ibáñez del Campo');
INSERT INTO REGION VALUES(12, 'de Magallanes y de la Antártica Chilena');
INSERT INTO REGION VALUES(13, 'Metropolitana');
INSERT INTO REGION VALUES(14, 'de Los Ríos');
INSERT INTO REGION VALUES(15, 'de Arica y Parinacota');
INSERT INTO REGION VALUES(16, 'de Ñuble');
/

-- POBLADO TABLA PAIS
INSERT INTO PAIS VALUES(SEQ_PAIS_ID_PAIS.NEXTVAL,'Chile');
INSERT INTO PAIS VALUES(SEQ_PAIS_ID_PAIS.NEXTVAL,'Argentina');
INSERT INTO PAIS VALUES(SEQ_PAIS_ID_PAIS.NEXTVAL,'Canadá');
INSERT INTO PAIS VALUES(SEQ_PAIS_ID_PAIS.NEXTVAL,'Australia');
INSERT INTO PAIS VALUES(SEQ_PAIS_ID_PAIS.NEXTVAL,'Alemania');
/

-- POBLADO TABLA PTJE_ESTADO_CIVIL

INSERT INTO PTJE_ESTADO_CIVIL VALUES ('Casado', 5);
INSERT INTO PTJE_ESTADO_CIVIL VALUES ('Conviviente civil', 4);
INSERT INTO PTJE_ESTADO_CIVIL VALUES ('Soltero', 3);
INSERT INTO PTJE_ESTADO_CIVIL VALUES ('Divorciado', 2);
INSERT INTO PTJE_ESTADO_CIVIL VALUES ('Viudo', 1);
/

-- POBLADO TABLA PTJE_OBJETIVO_EST
INSERT INTO PTJE_OBJETIVO_EST VALUES ('Excelente', 5);
INSERT INTO PTJE_OBJETIVO_EST VALUES ('Muy bueno', 4);
INSERT INTO PTJE_OBJETIVO_EST VALUES ('Bueno', 3);
INSERT INTO PTJE_OBJETIVO_EST VALUES ('Regular, 1');
/

-- POBLADO TABLA PTJE_RETRIBUCION
INSERT INTO PTJE_RETRIBUCION VALUES ('Excelente', 5);
INSERT INTO PTJE_RETRIBUCION VALUES ('Muy bueno', 4);
INSERT INTO PTJE_RETRIBUCION VALUES ('Bueno', 3);
INSERT INTO PTJE_RETRIBUCION VALUES ('Regular, 1');
/

-- POBLADO TABLA PTJE_DECL_INTERES
INSERT INTO PTJE_DECL_INTERES VALUES ('Excelente', 5);
INSERT INTO PTJE_DECL_INTERES VALUES ('Muy bueno', 4);
INSERT INTO PTJE_DECL_INTERES VALUES ('Bueno', 3);
INSERT INTO PTJE_DECL_INTERES VALUES ('Regular, 1');
/

-- POBLADO TABLA PTJE_EDAD
INSERT INTO PTJE_EDAD VALUES (18, 29, 5);
INSERT INTO PTJE_EDAD VALUES (30, 39, 3);
INSERT INTO PTJE_EDAD VALUES (40, 120, 1);
/

-- POBLADO TABLA PTJE_ANTEC_ACADEMICOS
INSERT INTO PTJE_ANTEC_ACADEMICOS VALUES (6.6, 7.0, 5);
INSERT INTO PTJE_ANTEC_ACADEMICOS VALUES (6.0, 6.5, 4);
INSERT INTO PTJE_ANTEC_ACADEMICOS VALUES (5.5, 5.9, 3);
INSERT INTO PTJE_ANTEC_ACADEMICOS VALUES (5.2, 5.4, 2);
INSERT INTO PTJE_ANTEC_ACADEMICOS VALUES (5.0, 5.1, 1);
/

-- POBLADO TABLA PTJE_ZONA_EXTREMA

-- cambiar nom_region por id_region (number)

INSERT INTO PTJE_ZONA_EXTREMA VALUES (15, 5);
INSERT INTO PTJE_ZONA_EXTREMA VALUES (1, 4);
INSERT INTO PTJE_ZONA_EXTREMA VALUES (11, 4);
INSERT INTO PTJE_ZONA_EXTREMA VALUES (12, 5);
/

-- POBLADO TABLA PTJE_EXP_LABORAL
INSERT INTO PTJE_EXP_LABORAL VALUES (6, 5); -- mayor o igual
INSERT INTO PTJE_EXP_LABORAL VALUES (5, 4);
INSERT INTO PTJE_EXP_LABORAL VALUES (4, 3);
INSERT INTO PTJE_EXP_LABORAL VALUES (3, 2);
INSERT INTO PTJE_EXP_LABORAL VALUES (2, 1);
/

-- POBLADO TABLA PTJE_ACT_DOCENCIA
INSERT INTO PTJE_DECL_INTERES VALUES ('Alta', 5);
INSERT INTO PTJE_DECL_INTERES VALUES ('Media', 3);
INSERT INTO PTJE_DECL_INTERES VALUES ('Baja, 1');
/

